# Generated by Django 4.2.17 on 2024-12-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RebateProgram',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('program_name', models.CharField(max_length=100)),
                ('rebate_percentage', models.DecimalField(decimal_places=2, max_digits=4)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('eligibility_criteria', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rebate_program',
            },
        ),
    ]
