# Generated by Django 4.2.17 on 2024-12-17 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rebate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=14)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('rebate_program_id', models.ForeignKey(db_column='rebate_program_id', on_delete=django.db.models.deletion.CASCADE, related_name='rebate_program_id', to='rebate.rebateprogram')),
            ],
            options={
                'db_table': 'transaction',
            },
        ),
    ]
